<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpPmXKR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpPmXKR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpPmXKR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpPmXKR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRpPmXKR\App_KernelDevDebugContainer([
    'container.build_hash' => 'RpPmXKR',
    'container.build_id' => '30dd9eeb',
    'container.build_time' => 1598447635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpPmXKR');
