<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOLSbuBd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOLSbuBd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOLSbuBd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOLSbuBd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOLSbuBd\App_KernelDevDebugContainer([
    'container.build_hash' => 'OLSbuBd',
    'container.build_id' => 'd20640c0',
    'container.build_time' => 1598540608,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOLSbuBd');
